language: node_js
dist: trusty
env:
  - DISPLAY=:99.0 CHROME_BIN=chromium-browser
branches:
  only:
    - master
node_js:
  - "7"
addons:
  firefox: latest
before_script:
  - sh -e /etc/init.d/xvfb start
